'use strict';
const leaderboardService={
 identity:null,run:null,category:'jump',request:0,
 async api(path,data){const response=await fetch('/api/'+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json',...(this.identity?{Authorization:'Bearer '+this.identity.token}:{})},body:data?JSON.stringify(data):undefined});let value;try{value=await response.json();}catch{throw Error('Global leaderboards are not connected on this address yet.');}if(!response.ok)throw Error(value.error||'Connection failed.');return value;},
 reset(){this.run=null;document.getElementById('leaderboard-sync').textContent='';},
 start(){if(!this.identity||this.run)return;this.run=this.api('start',{map:game.mapIndex}).catch(()=>null);},
 async finish(){const pending=this.run;if(!pending)return;const status=document.getElementById('leaderboard-sync');status.textContent='Saving global record…';this.run=null;const result={score:Math.floor(game.score),jump:Math.floor(game.bestJump||0),combo:game.maxChain?Math.min(6,game.maxChain+1):0,success:game.success};try{const receipt=await pending;if(!receipt){status.textContent='Record not saved online — connection unavailable.';return;}await this.api('finish',{...result,run:receipt.run});status.textContent='Saved to global leaderboards.';}catch(e){status.textContent=e.message;}},
 async load(){const request=++this.request,output=document.getElementById('board-rows'),status=document.getElementById('board-status');output.replaceChildren();status.textContent='Loading global records…';try{const data=await this.api('boards?category='+encodeURIComponent(this.category));if(request!==this.request)return;status.textContent=data.rows.length?'Updated now · UTC day '+data.day:'No records yet. Be the first!';for(const [index,row] of data.rows.entries()){const item=document.createElement('li'),rank=document.createElement('span'),name=document.createElement('strong'),value=document.createElement('b');rank.textContent=String(index+1).padStart(2,'0');name.textContent=row.name;value.textContent=row.value.toLocaleString()+(this.category==='streak'||this.category==='active'?' days':this.category==='combo'?'×':' pts');if(row.id===this.identity?.id)item.classList.add('is-you');item.append(rank,name,value);output.appendChild(item);}}catch(e){if(request===this.request)status.textContent=e.message;}},
 open(){setScreen('boards');document.getElementById('board-profile').hidden=!!this.identity;document.getElementById('board-player').textContent=this.identity?'Playing as '+this.identity.name:'Choose a nickname to submit your future runs.';this.load();},
};
try{const p=JSON.parse(localStorage.getItem('jumpbar-player'));if(p&&typeof p.id==='string'&&typeof p.token==='string'&&typeof p.name==='string')leaderboardService.identity=p;}catch{}
document.getElementById('boards-open').onclick=()=>{if(location.hostname==='latemake.github.io'){location.href='https://jumpbar.pages.dev/#save='+encodeURIComponent(btoa(JSON.stringify(campaign.data)));}else leaderboardService.open();};
if(location.hostname==='latemake.github.io')document.getElementById('boards-open').textContent='PLAY ONLINE · LEADERBOARDS ↗';
document.getElementById('boards-close').onclick=()=>{leaderboardService.request++;setScreen('menu');};
document.getElementById('board-refresh').onclick=()=>leaderboardService.load();
document.getElementById('board-category').onchange=e=>{leaderboardService.category=e.target.value;leaderboardService.load();};
document.getElementById('board-profile').onsubmit=async e=>{e.preventDefault();const button=document.getElementById('board-join'),status=document.getElementById('board-status');button.disabled=true;try{const result=await leaderboardService.api('players',{name:document.getElementById('board-nickname').value});leaderboardService.identity=result;try{localStorage.setItem('jumpbar-player',JSON.stringify(result));}catch{status.textContent='Your nickname will only last for this session.';}leaderboardService.open();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};
